package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MyUserAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMyUserAllPropertiesEquals(MyUser expected, MyUser actual) {
        assertMyUserAutoGeneratedPropertiesEquals(expected, actual);
        assertMyUserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMyUserAllUpdatablePropertiesEquals(MyUser expected, MyUser actual) {
        assertMyUserUpdatableFieldsEquals(expected, actual);
        assertMyUserUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMyUserAutoGeneratedPropertiesEquals(MyUser expected, MyUser actual) {
        assertThat(expected)
            .as("Verify MyUser auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMyUserUpdatableFieldsEquals(MyUser expected, MyUser actual) {
        assertThat(expected)
            .as("Verify MyUser relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getSurname()).as("check surname").isEqualTo(actual.getSurname()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMyUserUpdatableRelationshipsEquals(MyUser expected, MyUser actual) {}
}
