package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MyUserMyTestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMyUserMyTestAllPropertiesEquals(MyUserMyTest expected, MyUserMyTest actual) {
        assertMyUserMyTestAutoGeneratedPropertiesEquals(expected, actual);
        assertMyUserMyTestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMyUserMyTestAllUpdatablePropertiesEquals(MyUserMyTest expected, MyUserMyTest actual) {
        assertMyUserMyTestUpdatableFieldsEquals(expected, actual);
        assertMyUserMyTestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMyUserMyTestAutoGeneratedPropertiesEquals(MyUserMyTest expected, MyUserMyTest actual) {
        assertThat(expected)
            .as("Verify MyUserMyTest auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMyUserMyTestUpdatableFieldsEquals(MyUserMyTest expected, MyUserMyTest actual) {
        assertThat(expected)
            .as("Verify MyUserMyTest relevant properties")
            .satisfies(e -> assertThat(e.getGrade()).as("check grade").isEqualTo(actual.getGrade()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMyUserMyTestUpdatableRelationshipsEquals(MyUserMyTest expected, MyUserMyTest actual) {
        assertThat(expected)
            .as("Verify MyUserMyTest relationships")
            .satisfies(e -> assertThat(e.getMyUser()).as("check myUser").isEqualTo(actual.getMyUser()))
            .satisfies(e -> assertThat(e.getMyTest()).as("check myTest").isEqualTo(actual.getMyTest()));
    }
}
